# Generated by Django 3.2.5 on 2022-05-31 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roary', '0002_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
